/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package CapaGUI;

/**
 *
 * @author Lizandro Tanta
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        this.setTitle("Sistema de Ventas");
        this.setExtendedState(FormMenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        menuAlmacen = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuConfiguraciones = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USUARIO:");

        lblIdUsuario.setText("jLabel2");

        lblNombre.setText("jLabel3");

        lblApellidos.setText("jLabel4");

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(lblIdUsuario)
                .addGap(45, 45, 45)
                .addComponent(lblNombre)
                .addGap(45, 45, 45)
                .addComponent(lblApellidos)
                .addContainerGap(1092, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addContainerGap(724, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdUsuario)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidos))
                .addGap(28, 28, 28))
        );

        menuArchivo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\archives_icon_129343.png")); // NOI18N
        menuArchivo.setMnemonic('f');
        menuArchivo.setText("Archivo");

        openMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\cerrarSesionIcon.png")); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Cerrar Sesión");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(openMenuItem);

        saveMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\Salir.png")); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Salir");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(saveMenuItem);

        menuBar.add(menuArchivo);

        menuAlmacen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\alamcenIcono.png")); // NOI18N
        menuAlmacen.setMnemonic('e');
        menuAlmacen.setText("Almacén");

        cutMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\productos.png")); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Productos");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        menuAlmacen.add(cutMenuItem);

        copyMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\Categoria.png")); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Categoria");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        menuAlmacen.add(copyMenuItem);

        menuBar.add(menuAlmacen);

        menuCompras.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\comprasIcon.png")); // NOI18N
        menuCompras.setMnemonic('h');
        menuCompras.setText("Compras");

        contentsMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\ComprasM.png")); // NOI18N
        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Compras");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        menuCompras.add(contentsMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\proveedorIc.png")); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Proveedores");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        menuCompras.add(aboutMenuItem);

        menuBar.add(menuCompras);

        menuVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\ventasIcon.png")); // NOI18N
        menuVentas.setText("Ventas");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\VentasIc.png")); // NOI18N
        jMenuItem1.setText("Ventas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuVentas.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\clientesSub.png")); // NOI18N
        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuVentas.add(jMenuItem2);

        menuBar.add(menuVentas);

        menuConsultas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\ConsultasIcon.png")); // NOI18N
        menuConsultas.setText("Consultas");

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\VentasRealizadas.png")); // NOI18N
        jMenuItem3.setText("Ventas Realizadas");
        menuConsultas.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\ComprasRealizadas.png")); // NOI18N
        jMenuItem4.setText("Compras Realizadas");
        menuConsultas.add(jMenuItem4);

        menuBar.add(menuConsultas);

        menuConfiguraciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\configutacionIcon.png")); // NOI18N
        menuConfiguraciones.setText("Configuraciones");

        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\Confusuario.png")); // NOI18N
        jMenuItem5.setText("Config. Usuarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuConfiguraciones.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\empleados.png")); // NOI18N
        jMenuItem6.setText("Empleados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuConfiguraciones.add(jMenuItem6);

        menuBar.add(menuConfiguraciones);

        menuReportes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\reporte Icon.png")); // NOI18N
        menuReportes.setText("Reportes");
        menuBar.add(menuReportes);

        menuAyuda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\Ayuda.png")); // NOI18N
        menuAyuda.setText("Ayuda");

        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lizandro Tanta\\Documents\\NetBeansProjects\\SistemaVentas\\Ventas\\src\\resources\\icons\\ayudaIcon.png")); // NOI18N
        jMenuItem8.setText("Ayuda");
        menuAyuda.add(jMenuItem8);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        
        FormProductos fp = new FormProductos();
        contenedor.add(fp);
        fp.toFront();
        fp.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        
        FormCategoria fc = new FormCategoria();
        contenedor.add(fc);
        fc.toFront();
        fc.setVisible(true);
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        
        FormProveedor fp = new FormProveedor();
        contenedor.add(fp);
        fp.toFront();
        fp.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        FormCliente fc = new FormCliente();
        contenedor.add(fc);
        fc.toFront();
        fc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FormEmpleado fe = new FormEmpleado();
        contenedor.add(fe);
        fe.toFront();
        fe.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FormUsuario fu = new FormUsuario();
        contenedor.add(fu);
        fu.toFront();
        fu.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
       dispose();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        FormLogin fe = new FormLogin(); 
        fe.setVisible(true);
        fe.pack();
        this.setVisible(false);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        
        FormCompras fc = new FormCompras();
        contenedor.add(fc);
        fc.toFront();
        fc.setVisible(true);
        FormCompras.txtIdUsuario.setText(lblIdUsuario.getText());
        FormCompras.txtNombreUsuario.setText(lblNombre.getText()+" "+lblApellidos.getText());
        
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        FromVentas fc = new FromVentas();
        contenedor.add(fc);
        fc.toFront();
        fc.setVisible(true);
        FromVentas.txtIdUsuario.setText(lblIdUsuario.getText());
        FromVentas.txtNombreUsuario.setText(lblNombre.getText()+" "+lblApellidos.getText());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JLabel lblApellidos;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblNombre;
    private javax.swing.JMenu menuAlmacen;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuConfiguraciones;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
